/**
 * copy 复制值
 *//*lgwind*/
var Copy = [
	'引入jquery',"function addScript(url){ var script = document.createElement('script'); script.setAttribute('type','text/javascript'); script.setAttribute('src',url); document.getElementsByTagName('head')[0].appendChild(script);} if (typeof jQuery == 'undefined') {addScript('https://code.jquery.com/jquery-3.0.0.min.js');}",
	'本地redis客户端启动','redis-cli.exe -h 127.0.0.1 -p 6379 -a lgwind',
	'mywebGit','https://gitee.com/Lgwind/myweb.git',
	'nodeGit','https://gitee.com/Lgwind/node.git',
	'findNode','netstat -pan | grep 8081',
	'killNode', 'kill -9 ',
	'Tomcat服务器','D:\\Lgwind\\apache-tomcat-6.0.43\\bin\\',
	'查询端口','netstat -aon|findstr 8081',
	'登录0','$($(".dobest_input")[0]).val("HYZDGJ0");$($(".dobest_input")[1]).val("1974523704XH");$(".mycheckbox").click();setTimeout(function(){$(".dobest_de_btn").click();},300);',
	'登录小号','$($(".dobest_input")[0]).val("HYZDGJXH");$($(".dobest_input")[1]).val("1974523704XH");$(".mycheckbox").click();setTimeout(function(){$(".dobest_de_btn").click();},300);',
	'登录大号','$($(".dobest_input")[0]).val("HYZDGJ");$($(".dobest_input")[1]).val("1974523704FfF");$(".mycheckbox").click();$(".dobest_de_btn").click();',
	
];
/*lgwind*/

/**
 * ☆ link ☆链接变量
 *//*lgwind*/
var Link = [
    
    /*标题类型*/
	'个人办公',"{type}",
    /*
     * 个人办公
     */
    '备忘录','https://shimo.im/sheet/5mLitoYCU40ddY71/RIDOC',
    
    /*标题类型*/
	'常用网页',"{type}",
    /**
     * 常用网页
     */
	'UP','https://docs.qq.com/sheet/DQ0pLY0tvanNBS2xO?tab=BB08J2',
	//'最新疫情信息记录','https://docs.qq.com/sheet/DV3BVS0NtQUFXVXlI?tab=hzmyde&c=C2A0A0',
	'最新疫情','https://voice.baidu.com/act/newpneumonia/newpneumonia/?from=osari_pc_3',
    //'json格式化','https://www.json.cn/',
    'HTML源码','http://www.mycodes.net/166/',
    'RGB_Color','http://www.114la.com/other/rgb.htm',
    '颜色选择器','http://www.atool.org/colorpicker.php',
    '特殊符号大全','http://xh.5156edu.com/page/18466.html',
    'QQemail','https://mail.qq.com/',
    '163email','http://mail.163.com/',
    '12306','http://www.12306.cn/mormhweb/',
    'ASCLL码对照表','http://ascii.911cha.com/',
    '石墨文档','https://shimo.im/dashboard/updated',
    '包图网','https://ibaotu.com/guanggao/1-91646-0-91652-0-2.html',
    '微信网页版','https://wx2.qq.com/',
    //'Educational','http://www.gdou.edu.cn/jw/zf.html',
    'spzhangkun','http://i.youku.com/u/UMTE3Njc4ODM2',
    '坐标拾取器','http://api.map.baidu.com/lbsapi/getpoint/index.html',
    '元素周期表','http://www.zdic.net/appendix/f7.htm',
    'office模板文件下载','http://www.officeplus.cn/List.shtml?cat=PPT&tag=1',
    'Intelli IDEA安装教程','https://blog.csdn.net/yl1712725180/article/details/80309862',
    'PanBaidu.com','http://pandownload.com/index.html',
	'如何写出安全的API接口（参数加密+超时处理+私钥验证+Https）','https://www.cnblogs.com/shihaiming/p/6227542.html',
	'js压缩','http://tool.oschina.net/jscompress',
	'几种常见的JavaScript混淆和反混淆工具分析实战','https://blog.csdn.net/hefeng6500/article/details/80024810',
	'计算机软件保护条例','https://duxiaofa.baidu.com/detail?searchType=statute&from=aladdin_28231&originquery=%E8%AE%A1%E7%AE%97%E6%9C%BA%E8%BD%AF%E4%BB%B6%E4%BF%9D%E6%8A%A4%E6%9D%A1%E4%BE%8B&count=33&cid=e516a9d872a325cf6bc22c851d9e5ee6_law',
    'Oracle 11g 忘记sys用户密码和system用户密码的解决办法','https://blog.csdn.net/u011595939/article/details/79243107',
	'oracle sysdate 时间跟系统时间不一致 ','http://blog.sina.com.cn/s/blog_815eac890101av3z.html',
	'Windows CMD 命令修改本机ip和dns','https://blog.csdn.net/ffj0721/article/details/80305296',
	'chrome谷歌浏览器实现多用户登录','https://blog.csdn.net/qq_28863851/article/details/83896848',
	'免费下论文的网站','https://www.jianshu.com/p/34ed8c4285bc',
    /*标题类型*/
	'前端',"{type}",
    /**
     * 前端
     */
	'js滚轮事件','js的滚轮事件',
	'apollo配置中心','https://blog.csdn.net/xp_zyl/article/details/82111702?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.add_param_isCf&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.add_param_isCf',
	'JS浮点计算问题','https://www.cnblogs.com/Stephenchao/p/5743805.html',
	'HTML特殊字符编码对照表','https://www.jb51.net/onlineread/htmlchar.htm',
	'JavaScript 异步、栈、事件循环、任务队列','https://segmentfault.com/a/1190000011198232',
	'jquery获取dom元素身上的绑定事件的问题','https://www.cnblogs.com/ysxq/p/7120243.html',
	'Jquery获取dom上的绑定事件','https://www.cnblogs.com/413xiaol/p/7887129.html',
	'正则表达式','https://blog.csdn.net/zhuchangbo18/article/details/82055011',
	'Echarts.js数据可视化插件入门','https://www.jianshu.com/p/3a9dff6e2312',
	'原生JS实现Ajax及Ajax的跨域请求','https://www.cnblogs.com/2502778498spw/p/7784390.html',
	'AngularJS','https://www.runoob.com/angularjs/angularjs-directives.html',
	'web uploader','https://fex.baidu.com/webuploader/getting-started.html',
	'LayUI','https://www.layui.com/admin/std/dist/views/?from=bejson',
	'QDfuns','https://www.qdfuns.com/',
    'Threejs教程','http://www.hewebgl.com/article/articledir/1',
    '基于HTML5 Canvas实现小游戏','https://www.jianshu.com/p/f2a4e293f7f0',
    'HTML5 Canvas','http://www.runoob.com/html/html5-canvas.html',
    'jxls教程','https://blog.csdn.net/yuliqi0429/article/details/41907711',
    'jQuery选择器','../download_html/jQuery Select.html',
    'html状态码','../download_html/html state.html',
    'css样式大全','css.html',
    'W3School','https://www.w3cschool.cn/',
    'Runoob','http://www.runoob.com/',
    'Primeton NUI Demo页面','http://127.0.0.1:8080/default/demo/index.jsp',
    'Governor','http://127.0.0.1:8080/governor/governor/user/login.jsp',
    'jQuery','http://www.jq22.com/jquery-info18221',
    'layui','http://www.layui.com/doc/',
    'lagerui','http://www.ligerui.com/demo.html',
    'layer弹出层框架','http://layer.layui.com/hello.html',
    'treejs','http://www.treejs.cn/v3/api.php',
    'RegExp','http://www.w3school.com.cn/jsref/jsref_obj_regexp.asp',
    'RegExp','http://www.runoob.com/js/js-obj-regexp.html',
    '前端模板','http://sc.chinaz.com/tag_moban/QianDuan.html',
    'TypeScript 快速入门','https://www.w3cschool.cn/typescript/typescript-tutorial.html',
	'span 超过长度限制 隐藏并在鼠标移入时显示全部字段','https://blog.csdn.net/helei_qingzheng/article/details/79985066',
	'JQUERY 获取DIV宽度与高度','https://www.cnblogs.com/agansj/p/7840821.html',
	'$.ajax 中的contentType','https://www.cnblogs.com/htoooth/p/7242217.html',
	'视频解析汇总','https://www.bilibili.com/read/cv2856713',
	'RGB转换成灰度图像的一个常用公式','https://blog.csdn.net/fly_wt/article/details/86432886',
	'html空格代码','https://www.html.cn/qa/html5/19221.html',
    
    /*标题类型*/
	'后台',"{type}",
    /**
     * 后台
     */
	'加载springBean配置文件','http://c.biancheng.net/spring/ioc.html',
	'安装Xftp','https://blog.csdn.net/xc_123/article/details/92806570',
	'centos7下安装chrome','https://www.cnblogs.com/iouwenbo/p/10263229.html',
	'centos7下安装node','https://blog.csdn.net/xerysherryx/article/details/78920978',
	'centos7命令大全','https://blog.csdn.net/qq_40087415/article/details/79367151',
	'WMware上安装CentOS6','https://blog.csdn.net/weixin_42873937/article/details/81840094',
	'gitee提交项目','http://www.5imoban.net/jiaocheng/hbuilder/2018/0831/3407.html',
	'NodeJS免安装','https://blog.csdn.net/u011561335/article/details/81452157',
	'h5总链接','https://h5mota.com/',
	'熊猫胖','https://www.xmpan.com/1029.html',
	'Spring框架入门','http://c.biancheng.net/spring/',
	'idea帮助文档','https://www.jetbrains.com/help/idea/discover-intellij-idea.html',
	'idea使用教程','http://doc.yonyoucloud.com/doc/wiki/project/intellij-idea-tutorial/introduce.html',
	'【干货合集】Docker快速入门与进阶','https://cloud.tencent.com/developer/article/1004996',
	'XMLHttpRequest详解','https://blog.csdn.net/z550449054/article/details/80538623',
	'postman','https://blog.csdn.net/fxbin123/article/details/80428216',
	'java的Spring中@Value注解的使用','https://blog.csdn.net/xiaokanfuchen86/article/details/113051575',
	'idea git更新和提交代码','https://www.cnblogs.com/eyesfree/p/9202320.html',
	'HttpServletRequest request 获取form参数的两种方式','https://www.cnblogs.com/exmyth/p/6768937.html',
	'Java导出Excel（Poi详解）','https://blog.csdn.net/w893932747/article/details/89354979',
	'Java无需解压直接读取ZIP压缩包里的文件及内容','https://blog.csdn.net/Peacock__/article/details/92840156',
	'svn切换资源库','https://blog.csdn.net/qq_38746380/article/details/86023525',
	'Velocity 模板引擎快速生成代码','https://www.jianshu.com/p/f486655c44e5',
	'Maven常用插件','https://blog.csdn.net/HaosCoder/article/details/79524629',
	'Maven坐标详解','https://www.cnblogs.com/dyh004/p/11579421.html',
	'IntellJ IDEA 使用技巧之组件窗口设置','https://blog.csdn.net/GS_40826/article/details/83868398',
	'使用IDEA自带的Spring Initializr新建一个SpringBoot项目','https://blog.csdn.net/umbrellasoft/article/details/81632610',
	'idea创建springcloud项目图文教程(EurekaServer注册中心)','https://www.cnblogs.com/sddai/p/9898544.html cloud discovery',
	'idea git使用','https://blog.csdn.net/kjfdjjvbmc/article/details/92378697',
	'《微服务：从设计到部署》','https://docshome.gitbooks.io/microservices/content/',
	'nginx安装及部署','https://blog.csdn.net/qq_33454884/article/details/89212702',
	'Nginx修改默认端口80','https://blog.csdn.net/zengwende/article/details/86612463',
	'oracle截取字段中的部分字符串','https://www.cnblogs.com/qmfsun/p/4493918.html',
	'设计模式','http://c.biancheng.net/design_pattern/',
	'HTML5 WebSocket Study','https://blog.csdn.net/fenlin88l/article/details/89400195',
	'再eclipse查看某个java类属于哪个jar包','https://blog.csdn.net/csdnliuxin123524/article/details/73572836',
	'Apache Tomcat 集群配置','https://blog.csdn.net/qq_28883885/article/details/70227646',
	'Tomcat集群搭建超详细','https://blog.csdn.net/qq_35661171/article/details/78359681',
	'cas单点登录认证原理','https://www.cnblogs.com/tudou1223/p/9018423.html',
	'java.lang.Thread.State类','https://www.cnblogs.com/hushaojun/p/4323511.html',
	'Windows中使用jstack查看线程状态','https://blog.csdn.net/Brave_heart4pzj/article/details/101350107',
	'天气预报接口','https://blog.csdn.net/zsj777/article/details/102456224',
	'Kettle入门','https://www.lanhusoft.com/Article/723.html',
	'ActiveMQ','https://blog.csdn.net/qq_33404395/article/details/80590113',
	'ibatis复用SQL片段、引入片段 动态条件增加','https://www.cnblogs.com/zouhong/p/9802889.html',
	'java线程等待/通知机制及中断','https://blog.csdn.net/only06/article/details/52972218',
	'AQS（AbstractQueuedSynchronizer）','https://www.cnblogs.com/micrari/p/6937995.html',
	'ThreadPoolExecutor使用','https://www.jianshu.com/p/f030aa5d7a28',
	'ThreadPoolExecutor机制','https://www.cnblogs.com/zedosu/p/6665306.html',
	'Executor线程','https://www.cnblogs.com/fengsehng/p/6048610.html',
	'爬取视频','https://blog.csdn.net/Enderman_xiaohei/article/details/94718494',
	'JSoup快速入门','https://www.yiibai.com/jsoup/jsoup-quick-start.html',
	'java注解-最通俗易懂的讲解','https://blog.csdn.net/qq1404510094/article/details/80577555',
	'在spring中使用SqlMapClientTemplate操作数据库','https://blog.csdn.net/wangxy799/article/details/50553274',
	'简单的mybatis+spring+junit整合','https://blog.csdn.net/u011214505/article/details/52056127',
	'java操作html字符串','https://blog.csdn.net/chaojixiaozhu/article/details/78931406',
	'Servlet','https://www.runoob.com/servlet/servlet-intro.html',
	'Redis教程','https://www.runoob.com/redis/redis-tutorial.html',
	'Oracle动态性能表v$session和v$process','https://blog.csdn.net/haiross/article/details/17718383',
	'pyhton学习笔记之安装cx_Oracle模块那些事儿及操作oracle小实例','https://blog.csdn.net/hui_2016/article/details/76229276',
	'python爬虫项目','https://blog.csdn.net/u014044812/article/details/78894108',
	'Windows 平台安装 MongoDB','https://www.runoob.com/mongodb/mongodb-window-install.html',
	'spring mvc结构','https://www.cnblogs.com/ysocean/p/7375405.html',
	'普元EOS工作流引擎相关数据库表','https://blog.csdn.net/hoho_12/article/details/79276231',
	'Tomcat下4个配置文件详解','http://www.cnblogs.com/sunshine-1/p/8990044.html',
	'图灵社区','http://www.ituring.com.cn/',
	'idea搭建ssm框架','https://www.cnblogs.com/toutou/p/ssm_spring.html',
	'IntelliJ IDEA 常用设置讲解','https://blog.csdn.net/qq_16605855/article/details/78799585',
	//'测试地址','http://127.0.0.1:8080/default/lgwind/cjfk/index.jsp',
    '详解Tomcat 配置文件server.xml','https://www.cnblogs.com/kismetv/p/7228274.html',
    '流程状态和活动状态','http://doc.primeton.com/pages/viewpage.action?pageId=426445',
    'jar下载','http://www.java2s.com/Code/Jar/CatalogJar.htm',
    'EOS数据库','http://doc.primeton.com/pages/viewpage.action?pageId=1147946',
    'Eclipse快捷键','https://www.cnblogs.com/mq0036/p/4995390.html',
    'Oracle代码 规则','https://www.cnblogs.com/ylldbk/p/5613927.html',
    'Java1234','http://www.java1234.com/',
    'Oracle','http://www.51zxw.net/list.aspx?cid=616',
    'python','https://www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000',
    'python2.7','https://www.liaoxuefeng.com/wiki/001374738125095c955c1e6d8bb493182103fac9270762a000',
    'JUnit教程(易百)','https://www.yiibai.com/junit/',
    'JUnit教程(W3School)','https://www.w3cschool.cn/junit/',
    //'AEResource','http://www.rr-sc.com/forum-6-1.html',
    'Qt5_Study','http://blog.csdn.net/louis_815/article/details/54286544',
	'IntelliJ idea注册码','http://idea.lanyus.com/',
	'Failed to read artifact descriptor for xxx:jar的问题解决','https://blog.csdn.net/u010087830/article/details/72530266',
	'LODOP打印样例','http://www.c-lodop.com/LodopDemo.html',
	'JDK的bin目录下那些常见工具使用集锦','https://www.cnblogs.com/wangcheng-blog/p/jvm_tools.html',
	'通过jstack与jmap分析一次线上故障','https://blog.csdn.net/lengyue309/article/details/80590119',
	'tomcat文件目录结构及功能介绍','https://www.cnblogs.com/x-ll123/p/7080682.html',
	'java下划线与驼峰命名互转','https://www.cnblogs.com/zhuhui-site/p/10090880.html',
	'eclipse中svn插件的安装与使用','https://www.cnblogs.com/duanxz/p/3334660.html',
	'java应用程序自定义log4j配置文件位置','https://blog.csdn.net/softmaker_tao/article/details/72845226',
	'log4j.properties配置详解与实例','https://www.cnblogs.com/tengqiuyu/p/7535373.html',
	'部署servlet','https://blog.csdn.net/u013238020/article/details/79952966',
	'使用Commons-FileUpload组件实现文件上传','https://blog.csdn.net/wzy18210825916/article/details/81226511',
	'java 连接mongodb','https://www.cnblogs.com/wenbronk/p/6385935.html',
	'解决Oracle出现以0开头的小数，开头的0消失的问题','https://blog.csdn.net/qq_34909807/article/details/76270987',
	'Eclipse中使用复制粘贴功能非常卡的解决办法','https://blog.csdn.net/bell2008/article/details/9157545',
	'oracle安装','https://blog.csdn.net/wei_li_2015/article/details/80835614',
	'使用svn在idea中导入，更新，提交代码','https://blog.csdn.net/xusheng_Mr/article/details/77964519',
	'tomcat安装和配置','https://blog.csdn.net/gyshun/article/details/80920227',
	'IntelliJ IDEA如何设置maven仓库','https://jingyan.baidu.com/article/7f766dafe93d214101e1d039.html',
	'解决idea控制台中文乱码问题','https://blog.csdn.net/liu865033503/article/details/81094575',
	'idea配置热部署','https://blog.csdn.net/qq_16148137/article/details/99694566',
	'MyBatisPlus中updateById与updateAllColumnById方法区别','https://blog.csdn.net/BADAO_LIUMANG_QIZHI/article/details/89438482',
	'idea帮助文档','https://www.jetbrains.com/help/idea/2016.3/system-settings.html',
	'Java工具类---打印方法调用轨迹','https://www.cnblogs.com/masting/p/11243701.html',
	'IDEA 设置鼠标悬停提示方法的注释','https://blog.csdn.net/wsp1041428717/article/details/87931648',
	'Intellij Idea界面从桌面消失，任务栏可以看到，但怎么都点不出来 的解决办法','https://blog.csdn.net/bestcleaner/article/details/85269115?utm_source=distribute.pc_relevant.none-task',
	'IntelliJ IDEA 面板、菜单介绍','https://blog.csdn.net/const_/article/details/89638117',
	'Intellij IDEA 添加jar包的三种方式','https://www.cnblogs.com/shoshana-kong/p/10592292.html',
	'Java设计模式：23种设计模式全面解析（超级详细）','http://c.biancheng.net/design_pattern/',
	'idea中配置maven','http://c.biancheng.net/maven2/idea-maven-config.html',
	'解決IDEA Create Maven Project 卡在 Downloading plugins...问题','https://blog.csdn.net/weixin_40001125/article/details/91354129',
	'idea创建maven项目时一直在 Process Running','https://blog.csdn.net/BlackPlus28/article/details/80683192?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link&utm_relevant_index=2',
	'Intellij IDEA 中maven plugins 里的插件报错，有红色波浪线','https://blog.csdn.net/zy103118/article/details/108843096',
	'idea新建maven项目','http://c.biancheng.net/maven2/idea-build-maven.html',
	'IDEA执行Maven命令窗口','http://c.biancheng.net/maven2/idea-maven-command.html',
	'idea如何将web项目打成war包','https://blog.csdn.net/jdk_wangtaida/article/details/84101291',
	'maven 将jar包添加到本地仓库','https://blog.csdn.net/weixin_33978044/article/details/85983710?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_title~default-0.no_search_link&spm=1001.2101.3001.4242.1&utm_relevant_index=3',
	'idea创建spring boot项目','http://c.biancheng.net/spring_boot/example.html',
	'idea 弹出Server\'s certificate is not trusted 解决方法','https://blog.csdn.net/minolk/article/details/83215438',
	'在idea里面创建springboot项目没有src，pom等文件，创建springboot项目是空的','https://blog.csdn.net/weixin_46070315/article/details/108894558',
	'关于java:IDEA创建SpringBoot项目报Invalid-artifact-id','https://lequ7.com/guan-yu-javaidea-chuang-jian-springboot-xiang-mu-bao-invalidartifactid.html',
	'使用IDEA创建SpringBoot项目出现Request failed with status code 403','https://blog.csdn.net/learnpythonL/article/details/106172314',
	'idea中使用maven插件时中文乱码','https://blog.csdn.net/u_ascend/article/details/80733478',
	'idea热部署','https://blog.csdn.net/Mind_programmonkey/article/details/121399876?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_title~default-0.pc_relevant_paycolumn_v2&spm=1001.2101.3001.4242.1&utm_relevant_index=3',
	'IDEA设置Maven自动下载Jar包(关闭)','https://blog.csdn.net/Migumigu1316/article/details/102941027',
	'阿里云仓库搜索','https://developer.aliyun.com/mvn/search',
	'mysql-connector-java兼容：Cannot load driver class: com.mysql.cj.jdbc.Driver','https://blog.csdn.net/zxf1242652895/article/details/106379538',
	'了解spring三级缓存','https://www.jianshu.com/p/071555acaba5',
	'spring三级缓存','https://blog.csdn.net/weixin_42390873/article/details/113581473',
    'Lambda表达式','https://blog.csdn.net/ioriogami/article/details/12782141',
	'String、StringBuffer和StringBuilder类的区别','http://c.biancheng.net/view/5822.html',
	'Java正则表达式详解','http://c.biancheng.net/view/5812.html',
	'Java Pattern类和Matcher类的使用','http://c.biancheng.net/view/5814.html',
	'Reids的内部运作机制','https://www.cnblogs.com/wujuntian/p/9218961.html',
	'Spring关于三级缓存的那些事儿','https://blog.csdn.net/Erick_wyh/article/details/122573978',
	'java单例饿汉式和懒汉式','https://www.cnblogs.com/cdlyy/p/12846098.html',
	'Java JDK 动态代理（AOP）使用及实现原理分析','https://blog.csdn.net/jiankunking/article/details/52143504',
	'Java容器（二）-CurrentHashMap详解（JDK1.8）','https://blog.csdn.net/programerxiaoer/article/details/80040090',
	'图解HashMap为什么线程不安全？','https://blog.csdn.net/zzu_seu/article/details/106669757',
	
	/*标题类型*/
	'教程',"{type}",
    /**
     * 教程
     */
	'汇编语言','http://c.biancheng.net/asm/',
	'idea使用教程','http://doc.yonyoucloud.com/doc/wiki/project/intellij-idea-tutorial/interface-introduce.html',
    'idea帮助文档', 'https://www.jetbrains.com/help/idea/2016.3/system-settings.html',
	'《微服务：从设计到部署》','https://docshome.gitbooks.io/microservices/content/',
	'bootstrap4教程','https://www.w3cschool.cn/bootstrap4/',
	'Node.js教程','https://www.w3cschool.cn/nodejs/',
	'常见的神经网络模型大总结','https://blog.csdn.net/qq_24690701/article/details/81868048',
	'谷歌云申请','https://coderschool.cn/2598.html',
	'VBScript 教程','https://www.w3school.com.cn/vbscript/index.asp',
	'Eclipse快捷键大全','https://www.cnblogs.com/springl/p/8709260.html',
	'电脑CPU性能天梯图','http://www.mydrivers.com/zhuanti/tianti/cpu/',
	'电脑显卡性能天梯图','http://www.mydrivers.com/zhuanti/tianti/gpu/',
	'手机CPU性能天梯图','http://www.mydrivers.com/zhuanti/tianti/01/',
	'Win10计划任务+弹窗','https://blog.csdn.net/weixin_33754065/article/details/93230657',
	'MSDN下载iso镜像文件','http://msdn.itellyou.cn/',
	'Centos官网下载','https://www.centos.org/download/',
	'winXP激活码','http://www.windows7en.com/xp/3374.html',
	'阿里云镜像下载','https://opsx.alibaba.com/mirror',
	'XP激活','http://ask.zol.com.cn/x/1315373.html',
	'磁盘分区','https://jingyan.baidu.com/article/fd8044fae86fb55031137ae5.html',
	'远程桌面连接','http://www.uqidong.com/help/11125.html',
	'希腊','https://www.processon.com/diagraming/608262d1e0b34d0360cdb62a',
	'spring教程','http://c.biancheng.net/spring/what-is-spring.html',
	'Servlet教程','http://c.biancheng.net/servlet2/',
	'Maven教程','http://c.biancheng.net/maven2/',
	'Spring Boot框架教程','http://c.biancheng.net/spring_boot/',
	'java教程','http://c.biancheng.net/java/',
	'redis教程','https://www.runoob.com/redis/redis-tutorial.html',
	
    /*标题类型*/ 
	'娱乐',"{type}", 
    /**
     * 娱乐
     */
	'电影票房','https://piaofang.maoyan.com/dashboard',
	'老子-道德经','https://www.daodejing.org/laozi.html',
	'桵舞导航-动漫','https://all.cc/',
	'毛泽东选集','https://marxists.wikis.cc/chinese/maozedong/index.htm',
	'毛选-第一卷','https://www.bilibili.com/read/readlist/rl330029',
	'中文马克思主义文库','https://marxists.wikis.cc/chinese/index.html',
	'图书馆创世纪-中文','https://librarygenesis.net/zh/',
	'走读派读书导航','http://zoudupai.com/',
	'ORB:开放存储库','https://orb.binghamton.edu/',
	'南大事件与文本','https://ptext.nju.edu.cn/13340/list.htm',
	'科学技术哲学专业网','http://www.pstruc.org/',
	'主义主义传送门','https://www.processon.com/view/link/6081a821e401fd45d70436af',
	'马克思主义学院','http://szb.sqmc.edu.cn/',
	'教员博览','http://www.mzdbl.cn/maoxuan/index.html',
	'全国图书馆参考咨询联盟','http://www.ucdrs.superlib.net/',
	'中国国家图书馆','http://www.nlc.cn/',
	//'毛选-第二卷','https://www.bilibili.com/read/readlist/rl331197',
	//'毛选-第三卷','https://www.bilibili.com/read/readlist/rl334156',
	//'毛选-第四卷','https://www.bilibili.com/read/readlist/rl336027',
	//'毛选-第五卷','https://www.bilibili.com/read/readlist/rl336028',
	//'毛选-精选','https://b23.tv/Lrg62FS',
	'三十六计','https://sunzi.5000yan.com/36/',
	'萌娘百科','https://zh.moegirl.org.cn/Mainpage',
	'汽车内外构造详细图解','https://baijiahao.baidu.com/s?id=1707213221086567636&wfr=spider&for=pc',
	'公务员考试','http://gd.offcn.com/zg/gdsk/sj.html',
	'五百年来王阳明', 'https://tv.cctv.com/2017/04/17/VIDEZVE5Euu85SSkrolP14KP170417.shtml?spm=C53121759377.PpQpNjJyNZw2.0.0',
	'资源网','https://www.ziyuanm.com/zywz/',
	'迪声软件-音源','https://www.dsoundsoft.com/voice/',
	'资治通鉴-阅读-进行中','http://book.sbkk8.com/gudai/shishu/zizhitongjian/80337.html',
	'鬼灭之刃-观看-进行中','https://www.njmega.com/imomoe/7792-3-5.html',
	'漫威电影宇宙','https://baike.baidu.com/item/%E6%BC%AB%E5%A8%81%E7%94%B5%E5%BD%B1%E5%AE%87%E5%AE%99/3706007?fr=aladdin',
	'DC电影宇宙','https://baike.baidu.com/item/DC%E6%89%A9%E5%B1%95%E5%AE%87%E5%AE%99/18793877?fromtitle=DC%E7%94%B5%E5%BD%B1%E5%AE%87%E5%AE%99&fromid=15894245',
	'中医基础理论','http://www.zysj.com.cn/lilunshuji/jichulilun/index.html',
	'CCTV-13新闻','https://tv.cctv.com/live/cctv13/?spm=C28340.P4hQlpYBT2vN.ExidtyEJcS5K.25',
	'世界名著','https://www.cz2che.com/',
	'教材电子版','http://bp.pep.com.cn/jc/',
	'国家哲学社会科学文献中心','http://www.ncpssd.org/index.aspx',
	'纪录片-自然','https://list.youku.com/category/show/c_84_s_6_d_1_pr_BBC_g_%E8%87%AA%E7%84%B6.html?spm=a2ha1.12701310.app.5~5!2~5!2~5~5~DL!3~DD~A!5',
	'全历史','https://www.allhistory.com/',
	'趣历史','http://www.qulishi.com/',
	'二十四史','http://www.read126.cn/194c6894-51d5-4df3-a4bc-fa1282139f82.html',
	'史书典籍','https://www.shicimingju.com/book/index.html',
	'藏头诗制作','https://www.shicimingju.com/cangtoushi/index.html',
	'报纸网站导航','http://www.oofof.com/baojiis.php',
	'古典文学网-推荐','https://www.gdwxcn.com/',
	'中国儿童文学网-推荐','http://www.61w.cn/',
	'经典名著文学网-推荐','https://www.22738.net/',
	'汉语言文学网-推荐','http://www.hanwenxue.com/',
	'天涯知识库','http://book.sbkk8.com/',
	'华语文学网','http://www.myhuayu.com/',
	'26文学网','https://www.wenxue26.cn/',
	'青年文学网','http://sw.5xwx.com/portal.php',
	'短文学','https://www.duanwenxue.com/',
	'江山文学网','http://www.vsread.com/',
	'瑞文网','https://www.ruiwen.com/',
	'业余文学网','http://www.yeyuwenxue.com/',
	'中创文网','http://www.zgcxwxw.com/',
	'文心文学网','https://www.winshine52.com/',
	'觅涯网','http://www.miyia.com/shortIndex.htm',
	'学习啦文学网','http://wenxue.xuexila.com/',
	'麦林文学网','http://www.mailinstory.com/',
	'自贡文学网','http://www.zgwxw.net.cn/',
	'纵横文学网','http://www.zhwxwz.com/',
	'广东校园文学网','http://www.gdwenxue.com/',
	'吾爱文学网','http://www.2552.com.cn/',
	'中国外国文学网','http://foreignliterature.cass.cn/',
	'文登读书文学网','http://wx.whwd.com/',
	'诗词文学网','http://www.lyfyjxc.com/',
	'奔流文学网','http://www.benliuwang.com/',
	'作家网','http://www.zuojiawang.com/',
	'全息文学网','http://wenxue.quanxi.cc/',
	'火种公益文学网','http://www.huozwx.com/',
	'忽然花开文学网','http://www.huran.net/index.html',
	'青梓文学网','http://www.qzwxgzs.com/col.jsp?id=105',
	'翠屏文学网','http://www.cuipingwx.org.cn/',
	'世华文学网','http://baliwx.com/index.html',
	'青春文学网','http://www.fndpw.com/',
	'南京邮电大学开源软件镜像站','https://mirrors.njupt.edu.cn/',
	'清华大学开源软件镜像站','https://mirror.tuna.tsinghua.edu.cn/',
	'中国科大开源软件镜像站','https://ipv4.mirrors.ustc.edu.cn/',
	'网易开源镜像站','http://mirrors.163.com/',
	'阿里云开源镜像站','https://developer.aliyun.com/mirror/',
	'腾讯云开源镜像站','https://mirrors.cloud.tencent.com/',
	'谷歌学术镜像','https://ac.scmor.com/',
	'谷歌商店','https://www.chromefor.com/',
	'SCI-Hub论文下载可用网址链接','https://tool.yovisun.com/scihub/',
	'油管(youtube)','https://www.mirror.co.uk/',
    
    /*标题类型*/
	'Lgwind',"{type}",
    /**
     * Lgwind
     */
	//'矩阵计算','{ip_}/html/matrix.html',
	'HJC编辑器','{ip_}/module/lgwindUI/codeEditor/code.html',
	'面试鸭','https://www.mianshiya.com/',
	'mp4转gif','https://app.xunjiepdf.com/mp42gif/',
	'电视台','{ip_}/module/china/index.html',
	'小游戏平台','{ip_}/module/game71/index.html',
	'putBox','{ip_}/module/putBox/index.html',
	'piano','{ip_}/module/piano/index.html',
	'H5Kill','{ip_}/module/H5Kill/index.html',
	'元素周期表','{ip_}/module/elem/index.html',
	'dinosaur','{ip_}/module/treeShow/index.html',
	'dinosaurData','{ip_}/module/treeShow/dinosaur/disnosaur.html',
	'idea','{ip_}/html/idea.html',
	'口语','https://www.bilibili.com/video/BV124411G76C?from=search&seid=10419441060251588276',
    '#red#js/HTML格式化','http://tool.chinaz.com/Tools/jsformat.aspx',
	'#red#SQL美化','{ip_}/html/sqlBeautify.html',
    //'#red#Java方法调用','http://127.0.0.1:8080/default/lgwind/html/javaMethod.jsp?calssName=myMethod',
	'MyTaskRecord','https://docs.qq.com/sheet/DV21DRlJneFdybEt0?tab=rj5wdj&c=C9A0C0',
	//'联动更新测试页面','http://127.0.0.1:8080/default/dataExchange/syncServiceTest/syncServiceTest.jsp',
	'数据库对比','{ip_}/module/database/database.html',
	'yanzheng','{ip_}/module/count/yanzheng.html',
	'lgwindChat','{ip_}/module/lgwindChat/index.html',
	'rgb颜色选择器','{ip_}/module/rgb/rgb.html',
	'txtUpload','D:\EOS/ide/eclipse/workspace/z.com.lgwind.test/com.lgwind.test.common/src/webcontent/module/txtFile/txt.html',
	'ajax','{ip_}/html/ajax.html',
	'SQL查询','http://localhost:8770/Lgwind/sql.html',
	'Lgwind','file:///E:/HBuilderProject/Lgwind/index.html',
    'Lgwind搜索','{ip_}/html/sou.html',
    'NER','http://localhost:8770/NER',
    'YQ','http://localhost:8770/YQ',
    'Log','http://localhost:8770/Log',
    'SZYL','http://localhost:8770/SZYL',
    'Eclipse免安装版使用信息登记表','https://shimo.im/sheet/fpRoMjEmkrMgekH3?r=8411ZGK',
    //'考核','https://shimo.im/sheet/efs7oJ2b2nISmTw2/RIDOC',
    '远程数据库','https://rdsnext.console.aliyun.com/#/rdsList/cn-qingdao/basic/',
    'sanguosha测试服','http://web.sanguosha.com/test.html',
    '橡皮三国杀','https://github.com/EraserTeam/EraserSanGuoSha',
	'十周年','https://web.sanguosha.com/login/index.html',
    //'werewolfkill','WerewolfKilldrag.html',
    //'overlord','overlord.html',
    //'shadow_fight2','shadow_fight2.html',
    
];
/*lgwind*/

/**
 * 搜索按钮变量
 *//*lgwind*/
var Button = [
    'Translation', 'http://dict.youdao.com/w/{search}/#keyfrom=dict.top',
	'Baidu#ba$', 'https://www.baidu.com/s?wd={search}',
    '360搜索#360','https://www.so.com/s?q={search}',
    'Bing搜索#bi','https://cn.bing.com/search?q={search}',
    '雅虎搜索#yh','https://search.yahoo.com/search?p={search}',
    '搜狗搜索#sg','http://www.sogou.com/sogou?query={search}',
    '中国搜索#zg','http://www.chinaso.com/search/pagesearch.htm?q={search}',
    //'eos搜索','http://doc.primeton.com/dosearchsite.action?cql=siteSearch+~+"{search}"&queryString={search}',
	'汉典#hd','https://www.zdic.net/hans/{search}',
	'OALib图书馆','http://www.oalib.com/search?kw={search}',
	'玩加竞技#w','http://www.wanplus.com/lol/search?k={search}',
	'七麦数据#q','https://www.qimai.cn/search/android/market/6/search/{search}',
	//'fow.kr#fow','http://fow.kr/find/{search}',
	'国家统计局#g','http://www.stats.gov.cn/was5/web/search?channelid=288041&andsen={search}',
	'动漫搜索#dm','https://www.maigo.cc/vodsearch/-------------/?wd={search}',
	'去广告解析#qgg','https://z1.m1907.cn?jx={search}',
	'vip视频#jx','https://jx.bozrc.com:4433/player/?url={search}',
	//'vip视频#jx','https://jx.parwix.com:4433/player/?url={search}',
	//'音乐解析','https://music.sounm.com/?name={search}&type=netease',
	//'漫画人#mhr','http://www.dm5.com/manhua-list-pay2/',
	'布丁动漫#bd','https://dm.budingcy.com/',
	'风之动漫#fz','https://www.fzdm.org/',
	'人人影视#rr','http://www.ldssz.com/',
    'PanSou搜索#pan', 'http://www.pansou.com/?q={search}',
    'Bilibili搜索#b$', 'https://search.bilibili.com/all?keyword={search}',
	'Bv#bv','http://player.bilibili.com/player.html?bvid={search}',
	'Dilidili搜索#d', 'http://www.dilidili3.cc/search/-------------/?wd={search}',
    'AcFun搜索#a$', 'http://www.acfun.cn/search/?#query={search}',
    'FuLiQu搜索#fl','http://www.fuliqu.com/',
	'好看视频#hk','https://haokan.baidu.com/videoui/page/search?query={search}',
	'爱奇艺视频#aqy','https://so.iqiyi.com/so/q_{search}',
	'腾讯视频#tx','https://v.qq.com/x/search/?q={search}',
	'西瓜视频#xg','https://www.ixigua.com/search/{search}/?keyword={search}',
	'优酷视频#yk','https://so.youku.com/search_video/q_{search}',
	'搜狐视频#sh','https://so.tv.sohu.com/mts?box=1&wd={search}',
	'搜酷视频#sk','https://www.soku.com/nt/search/q_{search}',
	'PPTV视频#pp','http://sou.pptv.com/s_video?kw={search}&context=default',
	'央视视频#ys','https://search.cctv.com/search.php?qtext={search}&type=video',
	'荔枝网#lz','https://www.gdtv.cn/search?key=(search}',
	'芒果TV视频#mg','https://so.mgtv.com/so?k={search}',
	'乐视视频#ls','http://so.le.com/s?wd={search}',
    '百度百科#bk', 'https://baike.baidu.com/item/{search}',
    '百度贴吧#tb$', 'https://tieba.baidu.com/f?kw={search}',
    '百度图片#tp', 'http://image.baidu.com/search/index?tn=baiduimage&fm=result&ie=utf-8&word={search}',
    '百度知道#zd', 'https://zhidao.baidu.com/search?ct=17&pn=0&tn=ikaslist&rn=10&lm=0&ie=utf-8&word={search}',
    //'爱学术','https://s.ixueshu.com/index.html?q={search}',
    'minimp4搜索', 'http://www.minimp4.com/search?q={search}',
    //'Lgwind搜索','html/sou.html',
    'CSDN搜索#c', 'https://so.csdn.net/so/search/s.do?q={search}',
	'慕课搜索#mk','https://www.imooc.com/search/article?words={search}',
	'思否搜索#sf','https://segmentfault.com/search?q={search}',
	'云栖搜索#yx','https://yq.aliyun.com/search?q={search}',
	'简书搜素#js','https://www.jianshu.com/search?q={search}&page=1&type=note',
	'腾讯云搜索#txy','https://cloud.tencent.com/developer/search/article-{search}',
	'知乎搜索#zh', 'https://www.sogou.com/sogou?query={search}&insite=zhihu.com',
	'博客园搜索#bky','https://zzk.cnblogs.com/s/blogpost?w={search}',
	'51CTO博客搜索','https://blog.51cto.com/search/result?q={search}',
	'Oracle搜索#oracle','https://www.oracle.com/search/results?Ntk=SI-ALL5&Ntt={search}',
    //'one-piece', 'https://one-piece.cn/post/10{search}{replace_[^0-9]_}',
    //'jar包下载',"http://www.java2s.com/Code/Jar/{search.first}/Download{search}{replace_/._}{replace_-_}.htm",
	'jar包下载#jar','https://mvnrepository.com/search?q={search}',
    'w3cshool搜索#s','https://www.w3cschool.cn/search?w={search}',
    'runoob搜索#r','http://www.runoob.com/?s={search}',
    //'java1234','http://zhannei.baidu.com/cse/search?q={search}&s=1841543737020962857',
    '高德地图搜索#gd', 'https://www.amap.com/search?query={search}&city=440100&geoobj=113.299921%7C23.127141%7C113.309233%7C23.131798&zoom=17',
    '天地图搜索#tdt','http://www.tianditu.gov.cn/service/query.html?value={search}',
    '千千音乐搜索#qq','http://music.taihe.com/search?key={search}',
    'v5电影搜索#v5','https://v.sov5.cn/search?q={search}',
	'艾特网#atw','https://iiter.cn/',
	'历史地图#h','https://www.ageeye.cn/search/map/{search}',
	'依赖查询#yl','https://mvnrepository.com/search?q={search}',
	'华律网#xf','http://s.66law.cn/cse/search?q={search}&s=18259188589626635806&nsid=9',
	
];
/*lgwind*/

var friendLink = [
	'link','{ip}/module/ALink/link.html',
    //'link','{ip}/link.html',
	'bilibili#', 'https://space.bilibili.com/17347104/bangumi',
	'sgsGame#', 'https://web.sanguosha.com/login/index.html',
	'文档', 'https://docs.qq.com/desktop/',
	//'lifeRestart#', 'https://liferestart.syaro.io/view/index.html',	
	'github#','https://gitee.com/',//https://github.com/',
	'贴吧#','https://tieba.baidu.com/',
	'电视','{ip_}/module/china/index.html',
	'元素周期表','{ip_}/module/elem/index.html',
	//'元素周期表' : 'https://www.zdic.net/ts/fulu/yuansu/',
	'日志','http://localhost:8770/Log/log/logPage',
	'聊天','{ip_}/module/lgwindChat/index.html',
	'H5Kill','{ip_}/module/H5Kill/index.html',
	'idea', '{ip_}/module/idea/index.html',
	'海报','https://bbs.talkop.com/',
	//'Web#','http://120.77.42.190:8081/Myweb.html',
	'127#','http://127.0.0.1:8081/Myweb.html',
	//'云服务#','https://ecs.console.aliyun.com/?spm=5176.12818093.recommend.decs.536a16d0wKxbHj#/server/region/cn-shenzhen'
	'简历','https://i.51job.com/resume/standard_resume.php?lang=c&resumeid=369293514',
];

/**
 * 标题提示文字 快捷键
 *//*lgwind*/
var titleHint = 'Ctrl + F：在页面上查找'+'\n'
                +'Ctrl + H：打开历史记录面板'+'\n'
                +'Ctrl + T：新建标签页'+'\n'
                +'Ctrl + W：关闭当前标签页'+''+'\n'
                +'Ctrl + U：查看源代码'+'\n'
                +'Ctrl +加号(+)：页面缩放比例增加25%'+'\n'
                +'Ctrl +减号(-)：页面缩放比例减小25%'+'\n'
                +'Ctrl + Shift + R：进入阅读模式(需要网页提供支持)'+'\n'
                +'Ctrl + Shift + T：打开上次关闭的页面'+'\n'
                +'Ctrl + Shift + M：进入Web笔记功能'+'\n'
                +'Ctrl + Shift + F：切换输入法简繁体'+'\n'
                +'Ctrl + Shift + Delete：清缓存'+'\n'
                +'Shift + 空格键：切换全角半角输入'+'\n'
                +'Shift + win + enter / F11: 全屏'+'\n'
				+'Shift + Alt + s : Eclipse快捷鍵（生成get、set、toString）'+'\n'
				+'CTRL + SHIFT + F : 繁体简体切换'+'\n'
				+'taskschd.msc : 打开任务计划'+'\n'
				+'Alt+5 : 打开idea控制台'+'\n'
				+'ctrl+shift+" : 控制台全屏'+'\n'
				+'win+d" : 最小化/显示 所有应用'
				
				;
/*lgwind*/

/**
 * 标题 设置点击复制文字（填配置文件地址）
 *//*lgwind*/
var title_copy_text = 'E:\\lgwind\\Myweb\\Myweb\\js\\js-var.js';
/*lgwind*/
